### ISSUE TITLE
nltk 로드 문제

### ISSUE THREAD

**Issue by mannamman** [mannamman/newsCrawl#19]
nltk 로드 중 에러 발생

2021-12-20T04:31:40.944934ZTraceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py",
line 932, in _bootstrap_inner self.run() File "/usr/local/lib/python3.8/threading.py",
line 870, in run self._target(*self._args, **self._kwargs) File "/app/cloudRun.py", line 50, in run result = translater.translate(context) File "/app/translater.py", line 55, in translate context = self.__word_preprocess(context) File "/app/translater.py", line 43, in __word_preprocess word_tokens = word_tokenize(context) File "/usr/local/lib/python3.8/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize sentences = [text] if preserve_line else sent_tokenize(text, language) File "/usr/local/lib/python3.8/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize tokenizer = load(f"tokenizers/punkt/{language}.pickle") File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 750, in load opened_resource = _open(resource_url) File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 876, in _open return find(path_, path + [""]).open() File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 583, in find raise LookupError(resource_not_found) LookupError:

**Comment by mannamman** [comment]
제대로 모듈이 다운로드가 안된 모양.
RUN python3 -m nltk.downloader punkt -d /usr/local/nltk_data
RUN python3 -m nltk.downloader stopwords -d /usr/local/nltk_data
목적지를 지정해서 다운로드 되도록 수정
